theme: jekyll-theme-minimal
title: "Developer Blog"
description: "Developer and SRE blog, tutorials and workshop material. By octopusx :)"
logo: https://s.gravatar.com/avatar/ac58da143616046d71ec18b5d11a72e7?s=80